### ISSUE TITLE
Show lured pokemon as regular spawns, even when pokestops are off

### ISSUE THREAD

**Issue by robbertkl** [istornz/iPokeGo#201]
Currently, the web view of https://github.com/PokemonGoMap/PokemonGo-Map shows lured pokemons on the map as regular spawned pokemon, even when you have pokestops turned off.

iPokeGo however, does not show lured pokemon afaik. The only way to see them is to turn on pokestops and tap on the pokestops with lure, to see what pokemon is currently lured. This makes it impossible to see them all at once (have to tap every lured pokestop 1 by 1), and prevents getting notifications as well, I believe?

Would be awesome if they would just show up like regular pokemon, just like PokemonGo-Map does, and treat them just like normal spawns, i.e. enable filtering (favorite/common) and notifications.

**Comment by markvl91** [comment]
The problem is that lured pokemon don't really fit the model we're using for iPokeGo. Pokemon in this app are dependent on having a unique spawnpoint id, and more importantly, a despawn time. Lured pokemon have neither, which make them a bit more tricky to incorporate in the map. I'm sure in due time they'll get in, but for now, I hope you now have a better idea of why they're not in yet.

**Comment by robbertkl** [comment]
Thanks! I get the technical side makes it a bit tricky; it's just that from a user's perspective they are just like regular spawning pokemon. This is why PokemonGo-Map shows them like normal spawns, perhaps creating mock spawnpoint IDs?

However, on PokemonGo-Map, they do have a despawn time! Don't know where they get it from, but it must somehow be in the info as well.

Would just be great to have this one day; now I still have to keep an eye on the web view to see the lured pokemon.
