### ISSUE TITLE
[Enhancement] Fetch scan location from server

### ISSUE THREAD

**Issue by dmunozfer** [istornz/iPokeGo#231]
PokemonGo-Map send scan location coordinates in `http://hostaname-pokemongomap/loc`

`{
  "lat": 40.41564693411584, 
  "lng": -3.683897057250988
}`

Insted of load scan location from user preferences, would not it be better to get it from the server?
I do not know pogom, also have this option?

**Comment by dmunozfer** [comment]
Implemented in PR #251

**Comment by istornz** [comment]
Nice, thx.
I added this functionality for pogom.

**Comment by danielmj** [comment]
This functionality actually is not working for me. I think because there is a mismatch between the NSUserDefaults value: `server_type` and `SERVER_API_DATA_POKEMONGOMAP` in the `fetchScanLocationData` method.

Here are the values that mine is returning:
**server_type:** 
`%%server_addr%%/raw_data?pokemon=%%pokemon_display%%&pokestops=%%pokestops_display%%&gyms=%%gyms_display%%`

**SERVER_API_DATA_POKEMONGOMAP:** 
`%%server_addr%%/raw_data?pokemon=%%pokemon_display%%&pokestops=%%pokestops_display%%&gyms=%%gyms_display%%&spawnpoints=%%spawnpoints_display%%`

They dont equal, so it never actually pulls the scan location.
