### ISSUE TITLE
iOS App Review Issue: misleading content

### ISSUE THREAD

**Issue by jankcat** [istornz/iPokeGo#49]
From the beta review, in case you plan on pushing to the apple store:

Design - 4.1
Your app or its metadata contains misleading content. Specifically, your app creates a misleading association with Pokemon Go.

Next Steps
Please remove or revise any misleading content in your app and its metadata.
In addition, we recommend adjusting your app name so that the misleading element is used as a descriptor, not as part of the product name. 

For example, the following style is an acceptable format for names:
GreatApp - with tagline "for Pokemon Go"

**Comment by backmeupplz** [comment]
Just user PokeRadar or something :)

**Comment by hoangnn89** [comment]
Do we have to remove pokemon, team, gym... (pokemon go icons) from app? @jankcat

**Comment by istornz** [comment]
I'm waiting for a new app icon. When I have it I will try to submit.

**Comment by hoangnn89** [comment]
![screen shot 2016-07-27 at 8 18 57 pm](https://cloud.githubusercontent.com/assets/5293264/17176548/6e5ca6d4-5437-11e6-9c16-e52a7fd0dedf.png)

how do you select those options @jankcat ?

**Comment by istornz** [comment]
@hoangnn89 Actually, the app doesn't contains all license file for custom libs.

**Comment by hoangnn89** [comment]
but if we check NO then they definitely ask about those pokemon icons stuff, and we're doom

**Comment by blackhattristar** [comment]
Do you guys have a version that is totally independent that you're trying to submit to the Apple App Store?

**Comment by brntphish** [comment]
I have one built.... I just need to change my data source to a local trainer account I guess. 

https://m.facebook.com/story.php?story_fbid=1061613040574683&id=100001779903579&comment_id=1061748810561106&notif_t=feed_comment&notif_id=1469972088409686&ref=m_notif

**Comment by Chidiemeh184** [comment]
I have this same problem ....

Apple said 

"
Next Steps

Please remove or revise any misleading content in your app and its metadata.

In addition, we recommend adjusting your app name so that the misleading element is used as a descriptor, not as part of the product name. For example, the following style is an acceptable format for names

"

they also attached my screenshots and icon

What I'm trying to understand ...

1. Should I just change the name of the in iTunes connect or
2. Should I change bundle id, profile, and have to rebuild with new name in all the codes?
3. Do they mean like just change the name so that the icon and screenshot will be fine, meaning
    I don't have to change the icon and screenshot again( as the new name will be fit for the images).
4. Please any other explanation

**Comment by AbelIngrand** [comment]
Did they say nothing about the background hack or your submitted versions didn't include it ?

**Comment by yuedong56** [comment]
it's mine, but I dont know how to change it, just change the app name?

Design - 4.1


Your app or its metadata contains misleading content. Specifically, your app creates a misleading association with iPhone￼.

Next Steps

Please remove or revise any misleading content in your app and its metadata.

In addition, we recommend adjusting your app name so that the misleading element is used as a descriptor, not as part of the product name. For example, the following style is an acceptable format for names:

PutYourUniqueAppNameHere - with tagline "for iPhone￼”

**Comment by Chidiemeh184** [comment]
Try to change the name and screenshots and re upload it
